#!/bin/bash
source ~/openrc
source .network >& /dev/null

if ! nova delete test_vm ; then
 echo perhaps you did not create a vm?
 echo continuing...
fi

PRIV_SUBNET_ID=`quantum subnet-list | grep '192.' | awk -F' ' '{print $2}'`
FLOAT_ID=`quantum floatingip-list | grep 192 | awk -F' ' '{print $2}'`
 if ! quantum floatingip-delete $FLOAT_ID >&/dev/null ; then
  echo perhaps you did not create a floating ip?
  echo continuing...
 fi

if ! quantum router-gateway-clear private_router_1 ; then
 echo 'could not clear router gateway'
fi

if ! quantum net-delete public  ; then
 echo 'public net not deleted'
fi
if ! quantum net-delete private ; then
 echo 'private net not delted'
fi

if ! quantum router-delete private_router_1 ; then
 echo 'router not delted'
fi
if ! [ -z ${PRIV_IP} ] && route del -net ${PRIV_IP}/${PRIV_CIDR} ; then
  echo 'metadata route not found'
fi

if ! quantum-netns-cleanup ; then
 echo 'quantum-netns-cleanup failed!'
fi
exit 0


