#!/bin/bash
source ~/openrc
source .network >& /dev/null

function sleep_count  () {
# pass in a time (usually in seconds) and a message ( in "")
echo -n $2
  count=1
  while [ $count -le $1 ]
  do
    echo -n '. '
    sleep 1
    (( count ++ ))
  done
}

DEL_STAT=`nova delete test_vm | grep status | awk -F' ' '{print $4}'`
echo "Waiting for VM to delete"
while [ ! -z "${DEL_STAT}" ]; do
 DEL_STAT=`nova show test_vm | grep status | awk -F' ' '{print $4}'`
 sleep_count 5 " . "
 if [ -z "${DEL_STAT}" ]; then
   break
 fi
done

IMAGE_ID=`glance index | grep 'test' | head -1 |  awk -F' ' '{print $1}'`
PRIV_SUBNET_ID=`quantum subnet-list | grep ${PUB_IP} | awk -F' ' '{print $2}'`

OIFS=$IFS
IFS='.'
ip=(${PUB_IP})
IFS=$OIFS
PRIV_SUB_SRC="${ip[0]}.${ip[1]}.${ip[2]}"
echo "Deleting floating IP from Subnet ${PRIV_SUB_SRC}"
FLOAT_ID=`quantum floatingip-list | grep ${PRIV_SUB_SRC} | awk -F' ' '{print $2}'`
 if ! quantum floatingip-delete $FLOAT_ID >&/dev/null ; then
  echo perhaps you did not create a floating ip?
  echo continuing...
 fi

if ! quantum router-gateway-clear private_router_1 ; then
 echo 'could not clear router gateway'
fi

if ! quantum net-delete public  ; then
 echo 'public net not deleted'
fi
if ! quantum net-delete private ; then
 echo 'private net not deleted'
fi

if ! quantum router-delete private_router_1 ; then
 echo 'router not deleted'
fi
if ! [ -z ${PRIV_IP} ] && route del -net ${PRIV_IP}/${PRIV_CIDR} ; then
  echo 'metadata route deleted'
fi
if ! nova secgroup-delete sec_test ; then
 echo 'no sec group defined?'
fi
if ! nova keypair-delete key_test ; then
 echo 'no key pair defined?'
fi
if ! rm -rf /tmp/{id,test}* ; then
 echo 'nothing in /tmp?'
fi
if [ ${IMAGE_ID} ] ; then
  if ! glance image-delete $IMAGE_ID ; then
    echo 'can not delete the test imgae'
  fi
fi

if ! quantum-netns-cleanup ; then
 echo 'quantum-netns-cleanup failed!'
fi
exit 0


